# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from cluster_master.proto import agent_pb2 as agent__pb2


class AgentServerStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.TaskStart = channel.unary_unary(
            '/tesra.AgentServer/TaskStart',
            request_serializer=agent__pb2.Proto.SerializeToString,
            response_deserializer=agent__pb2.Proto.FromString,
        )
        self.TaskStop = channel.unary_unary(
            '/tesra.AgentServer/TaskStop',
            request_serializer=agent__pb2.Proto.SerializeToString,
            response_deserializer=agent__pb2.Proto.FromString,
        )


class AgentServerServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def TaskStart(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskStop(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'TaskStart': grpc.unary_unary_rpc_method_handler(
            servicer.TaskStart,
            request_deserializer=agent__pb2.Proto.FromString,
            response_serializer=agent__pb2.Proto.SerializeToString,
        ),
        'TaskStop': grpc.unary_unary_rpc_method_handler(
            servicer.TaskStop,
            request_deserializer=agent__pb2.Proto.FromString,
            response_serializer=agent__pb2.Proto.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'tesra.AgentServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
