# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sch.proto

from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (
        lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(name='sch.proto', package='sch', syntax='proto3', serialized_options=_b('Z\003sch'), serialized_pb=_b(
    '\n\tsch.proto\x12\x03sch\"F\n\x05Proto\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0b\n\x03seq\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\x32u\n\x07Skylark\x12#\n\tHeartBeat\x12\n.sch.Proto\x1a\n.sch.Proto\x12\x1f\n\x05Login\x12\n.sch.Proto\x1a\n.sch.Proto\x12$\n\nTaskStatus\x12\n.sch.Proto\x1a\n.sch.ProtoB\x05Z\x03schb\x06proto3'))


_PROTO = _descriptor.Descriptor(
    name='Proto',
    full_name='sch.Proto',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='version', full_name='sch.Proto.version', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='seq', full_name='sch.Proto.seq', index=1,
            number=2, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='sch.Proto.timestamp', index=2,
            number=3, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='body', full_name='sch.Proto.body', index=3,
            number=4, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=18,
    serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Proto'] = _PROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto = _reflection.GeneratedProtocolMessageType('Proto', (_message.Message,), dict(
    DESCRIPTOR=_PROTO,
    __module__='sch_pb2'
    # @@protoc_insertion_point(class_scope:sch.Proto)
))
_sym_db.RegisterMessage(Proto)


DESCRIPTOR._options = None

_SKYLARK = _descriptor.ServiceDescriptor(
    name='Skylark',
    full_name='sch.Skylark',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=90,
    serialized_end=207,
    methods=[
        _descriptor.MethodDescriptor(
            name='HeartBeat',
            full_name='sch.Skylark.HeartBeat',
            index=0,
            containing_service=None,
            input_type=_PROTO,
            output_type=_PROTO,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='Login',
            full_name='sch.Skylark.Login',
            index=1,
            containing_service=None,
            input_type=_PROTO,
            output_type=_PROTO,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='TaskStatus',
            full_name='sch.Skylark.TaskStatus',
            index=2,
            containing_service=None,
            input_type=_PROTO,
            output_type=_PROTO,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_SKYLARK)

DESCRIPTOR.services_by_name['Skylark'] = _SKYLARK

# @@protoc_insertion_point(module_scope)
