# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster_raft/raft_grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cluster_raft/raft_grpc.proto',
  package='raft',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x63luster_raft/raft_grpc.proto\x12\x04raft\"\x1a\n\x0cGetStatusReq\x12\n\n\x02ts\x18\x01 \x01(\t\"*\n\x0cGetStatusRes\x12\n\n\x02ts\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"C\n\x0fIsRegisteredReq\x12\n\n\x02ts\x18\x01 \x01(\t\x12\x10\n\x08need_set\x18\x02 \x01(\x08\x12\x12\n\nset_status\x18\x03 \x01(\x08\">\n\x0fIsRegisteredRes\x12\n\n\x02ts\x18\x01 \x01(\t\x12\x0f\n\x07\x63hanged\x18\x02 \x01(\x08\x12\x0e\n\x06status\x18\x03 \x01(\x08\x32\x80\x01\n\x0bRaftService\x12\x33\n\tGetStatus\x12\x12.raft.GetStatusReq\x1a\x12.raft.GetStatusRes\x12<\n\x0cIsRegistered\x12\x15.raft.IsRegisteredReq\x1a\x15.raft.IsRegisteredResb\x06proto3')
)




_GETSTATUSREQ = _descriptor.Descriptor(
  name='GetStatusReq',
  full_name='raft.GetStatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='raft.GetStatusReq.ts', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=64,
)


_GETSTATUSRES = _descriptor.Descriptor(
  name='GetStatusRes',
  full_name='raft.GetStatusRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='raft.GetStatusRes.ts', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='raft.GetStatusRes.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=108,
)


_ISREGISTEREDREQ = _descriptor.Descriptor(
  name='IsRegisteredReq',
  full_name='raft.IsRegisteredReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='raft.IsRegisteredReq.ts', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_set', full_name='raft.IsRegisteredReq.need_set', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_status', full_name='raft.IsRegisteredReq.set_status', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=177,
)


_ISREGISTEREDRES = _descriptor.Descriptor(
  name='IsRegisteredRes',
  full_name='raft.IsRegisteredRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='raft.IsRegisteredRes.ts', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='changed', full_name='raft.IsRegisteredRes.changed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='raft.IsRegisteredRes.status', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=241,
)

DESCRIPTOR.message_types_by_name['GetStatusReq'] = _GETSTATUSREQ
DESCRIPTOR.message_types_by_name['GetStatusRes'] = _GETSTATUSRES
DESCRIPTOR.message_types_by_name['IsRegisteredReq'] = _ISREGISTEREDREQ
DESCRIPTOR.message_types_by_name['IsRegisteredRes'] = _ISREGISTEREDRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetStatusReq = _reflection.GeneratedProtocolMessageType('GetStatusReq', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATUSREQ,
  __module__ = 'cluster_raft.raft_grpc_pb2'
  # @@protoc_insertion_point(class_scope:raft.GetStatusReq)
  ))
_sym_db.RegisterMessage(GetStatusReq)

GetStatusRes = _reflection.GeneratedProtocolMessageType('GetStatusRes', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATUSRES,
  __module__ = 'cluster_raft.raft_grpc_pb2'
  # @@protoc_insertion_point(class_scope:raft.GetStatusRes)
  ))
_sym_db.RegisterMessage(GetStatusRes)

IsRegisteredReq = _reflection.GeneratedProtocolMessageType('IsRegisteredReq', (_message.Message,), dict(
  DESCRIPTOR = _ISREGISTEREDREQ,
  __module__ = 'cluster_raft.raft_grpc_pb2'
  # @@protoc_insertion_point(class_scope:raft.IsRegisteredReq)
  ))
_sym_db.RegisterMessage(IsRegisteredReq)

IsRegisteredRes = _reflection.GeneratedProtocolMessageType('IsRegisteredRes', (_message.Message,), dict(
  DESCRIPTOR = _ISREGISTEREDRES,
  __module__ = 'cluster_raft.raft_grpc_pb2'
  # @@protoc_insertion_point(class_scope:raft.IsRegisteredRes)
  ))
_sym_db.RegisterMessage(IsRegisteredRes)



_RAFTSERVICE = _descriptor.ServiceDescriptor(
  name='RaftService',
  full_name='raft.RaftService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=244,
  serialized_end=372,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='raft.RaftService.GetStatus',
    index=0,
    containing_service=None,
    input_type=_GETSTATUSREQ,
    output_type=_GETSTATUSRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IsRegistered',
    full_name='raft.RaftService.IsRegistered',
    index=1,
    containing_service=None,
    input_type=_ISREGISTEREDREQ,
    output_type=_ISREGISTEREDRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAFTSERVICE)

DESCRIPTOR.services_by_name['RaftService'] = _RAFTSERVICE

# @@protoc_insertion_point(module_scope)
